#! /bin/sh
#
# Copyright (c) 2003,2004,2012,2013 Andreas Lang-Nevyjel/init.at
#
#
# RedHat stuff
# chkconfig: 2345 79 21
# description: cluster-config-server
#
### BEGIN INIT INFO
# Provides:      cluster-config-server
# Required-Start: $network $syslog logging-server
# Required-Stop: $network $syslog logging-server
# Should-Start: mysql postgresql
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Description:   starts cluster-config-server
### END INIT INFO

export SYSTEMD_NO_WRAP="1"
if [ -f /etc/rc.status ] ; then
    . /etc/rc.status
else
    . /etc/rc.status_suse
fi
. /etc/init.d/ics_tools.sh

SERVER_BIN=/opt/cluster/sbin/cluster-config-server.py
PYTHON_BIN=/usr/bin/python-init
SERVER_PID=/var/run/cluster-config-server/cluster-config-server.pid
SERVER_ARGS=""
SERVER_USER="idccs"
SERVER_GROUP="idg"

test -x ${SERVER_BIN} || exit 5
test -x ${PYTHON_BIN} || exit 5

rc_reset

id ${SERVER_USER} > /dev/null || { echo "User ${SERVER_USER} for ${SERVER_BIN} not found, exiting..." ; rc_failed 6 ; rc_exit ; }
[ "`id ${SERVER_USER} -g -n`" != "${SERVER_GROUP}" ] && { echo "Group ${SERVER_GROUP} for ${SERVER_BIN} not found, exiting..." ; rc_failed 6 ; rc_exit ; }

export HOSTNAME=`/bin/hostname`
case "$1" in
    start)
        echo -n "Starting cluster-config-server.py"
        if [ -f ${SERVER_PID} ] ; then
            echo -n " ... already running"
        else
            ${SERVER_BIN} ${SERVER_ARGS} ${SERVER_ARGS}
        fi
        rc_status -v
        ;;
    stop)
        echo -n "Stopping cluster-config-server.py"
        if [ -f ${SERVER_PID} ] ; then
            kill -s 15 `cat ${SERVER_PID} | head -n 1` || rc_failed
        else
            rc_failed
        fi
        rm -f ${SERVER_PID}
        rc_status -v
        ;;
    force-stop)
        echo -n "Force stopping cluster-config-server.py"
        if [ -f ${SERVER_PID} ] ; then
            kill -9 `cat ${SERVER_PID} ` || rc_failed
        else
            rc_failed
        fi
        rm -f ${SERVER_PID}
        rc_status -v
        ;;
    status)
        echo -n "Checking cluster-config-server.py..."
        check_threads_ok && {
            rc_status -v ; 
        } || {
            if ${SERVER_BIN} -C ; then
                check_threads || rc_failed 
                rc_status -v
            else
                rc_status -s
            fi
        } 
        ;;
    restart)
        echo "Restarting $(basename $SERVER_BIN)"
        $0 stop && sleep 2 ; $0 start || return=$rc_failed
        ;;
    force-restart)
        echo "Force-restarting $(basename $SERVER_BIN)"
        $0 force-stop && sleep 2 ; $0 start || return=$rc_failed
        ;;
    *)
        echo "Usage: $0 {start|stop|status|force-stop|restart|force-restart}"
        exit 1
        ;;
esac

rc_exit
