#!/usr/bin/python-init -Otu

import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "initat.cluster.settings")

from django.core.management import execute_from_command_line

def main():
    execute_from_command_line(["notimportant", "shell"])

if __name__ == "__main__":
    main()
