#!/bin/bash
# Copyright (c) 2001 init.at
#
### BEGIN INIT INFO
# Provides:      loadmodules
# Required-Start:
# Required-Stop:
# Default-Start: 3 5
# Default-Stop:
# Description:   load modules at startup
### END INIT INFO

. /etc/rc.config

base=${0##*/}
link=${base#*[SK][0-9][0-9]}

rc_reset

return=$rc_done
case "$1" in
    start)  echo -n "Loading modules..."
            unset mods
            if [ -f /etc/modules ] ; then
              mods=`cat /etc/modules`
            fi

            if [ "${mods:-0}" == "0" ] ; then
              echo -n " no modules to load"
            else
              echo -n " "
              while read modl ; do
                mod=`echo $modl | cut -d " " -f 1`
                modarg=`echo $modl | cut -d " " -f 2-`
                if [ ! ${mod:-0} == 0 ] ; then    
                  modprobe $mod $modarg > /dev/null 2>&1 && {
                     echo -n "OK-" ;
                  } || {
                    echo -n "FAILED-" ; rc_failed 2 ;
                  }
                fi
              done < /etc/modules
            fi
            rc_status -v    
	    ;;
    stop)
            ;;
    status)
            echo -n "Showing loaded modules..."
            rc_status -v
            /sbin/lsmod
            ;;
    *)      echo "Usage: $0 {start|stop|status}"
            exit 1
esac

test "$return" = "$rc_done" || exit 1
exit 0
