# Projectwide configurations

PYTHON=python-init

INSTALL=install
INSTALL_OPTS=-p

LN=ln

DOCDIR=/usr/share/doc/packages/init.at/host-monitoring
CONFDIR=/etc/sysconfig/host-monitoring.d
SCRIPTDIR=/usr/bin
CLUSTERBIN=/opt/cluster/sbin

VERSION=
RELEASE=
