# Projectwide configurations

PYTHON=python-init

INSTALL=install
INSTALL_OPTS=-p

LN=ln

DOCDIR=/usr/share/doc/packages/init.at/host-monitoring
CONFDIRROOT=/etc/sysconfig
CONFDIR=${CONFDIRROOT}/host-monitoring.d
SCRIPTDIR=/usr/bin
CLUSTERBIN=/opt/cluster/sbin
INITDIR=/etc/init.d
SBIN=/usr/sbin
LOCALSBIN=/usr/local/sbin

VERSION=
RELEASE=
