#!/bin/bash
. ../devrc
NAME=cluster-server
rpmd=/usr/src/packages
cp ${NAME}.spec ${rpmd}/SPECS
tar -czvf ${rpmd}/SOURCES/${NAME}.tgz cluster-server.py cluster-server cluster_server_messages.py README LICENSE.GPL

prepare_spec
cd $rpmd/SPECS
build_rpm noarch
install_file
