#!/bin/bash
#
# Copyright (c) 2003-2007,2012-2014 Andreas Lang-Nevyjel init.at
#
# RedHat stuff
# chkconfig: 2345 79 21
# description: rrd-grapher
#

### BEGIN INIT INFO
# Provides:      rrd-grapher
# Required-Start: $network logging-server meta-server
# Should-Start: mysql
# Required-Stop: $network logging-server meta-server
# Should-Stop: mysql
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Description:   start rrd-grapher
### END INIT INFO

export SYSTEMD_NO_WRAP="1"
if [ -f /etc/rc.status ] ; then
    . /etc/rc.status
else
    . /etc/rc.status_suse
fi
. /etc/init.d/ics_tools.sh

if [ -f /etc/redhat-release ] ; then
    export RH=1
    . /etc/init.d/functions
else
    export RH=0
fi
# check for debian
if [ -f /etc/debian_version ] ; then
    export DB=1
else
    export DB=0
fi

ACT_SERVER_TYPE=grapher
SERVER_BIN=/opt/cluster/sbin/rrd-${ACT_SERVER_TYPE}.py
SERVER_PID=/var/run/rrd-${ACT_SERVER_TYPE}/rrd-${ACT_SERVER_TYPE}.pid
PYTHON_BIN=/usr/bin/python-init
SERVER_ARGS=""
SERVER_USER="idrrd"
SERVER_GROUP="idg"
META_FILE="/var/lib/meta-server/rrd-${ACT_SERVER_TYPE}"
# set default font
export RRD_DEFAULT_FONT="verdana 8"

test -x ${SERVER_BIN} || exit 5
test -x ${PYTHON_BIN} || exit 5

rc_reset

id ${SERVER_USER} > /dev/null 2>&1 || { echo "User ${SERVER_USER} for ${SERVER_BIN} not found, exiting..." ; rc_failed 6 ; rc_exit ; }

[ "`id ${SERVER_USER} -g -n`" != "${SERVER_GROUP}" ] && { echo "Group ${SERVER_GROUP} for ${SERVER_BIN} not found, exiting..." ; rc_failed 6 ; rc_exit ; }

export HOSTNAME=`/bin/hostname`
case "$1" in
    start)
        echo -n "Starting rrd-${ACT_SERVER_TYPE}.py"
        if [ -f ${SERVER_PID} ] ; then
            echo -n " ... already running"
        else
	    ${SERVER_BIN} ${SERVER_ARGS}
        fi
        rc_status -v
        ;;
    stop)
        echo -n "Stopping rrd-${ACT_SERVER_TYPE}.py ... "
        if [ -f ${SERVER_PID} ] ; then
            kill -s 15 `cat ${SERVER_PID} | head -n 1` || rc_failed
        else
            rc_failed
        fi
        rm -f ${SERVER_PID}
        rc_status -v
        ;;
    force-stop)
        echo -n "Force stopping rrd-${ACT_SERVER_TYPE}.py"
        if [ -f ${SERVER_PID} ] ; then
            kill -9 `cat ${SERVER_PID} ` || rc_failed
        else
            rc_failed
        fi
        rm -f ${SERVER_PID} ${META_FILE}
        rc_status -v
        ;;
    status)
        echo -n "Checking rrd-${ACT_SERVER_TYPE}.py..."
        check_threads_ok && {
            rc_status -v ; 
        } || {
            if ${SERVER_BIN} -C ; then
                check_threads || rc_failed 
                rc_status -v
            else
                rc_status -s
            fi
        } 
        ;;
    reload)
        echo "Reloading $(basename $SERVER_BIN)"
        if [ -f ${SERVER_PID} ] ; then
            kill -HUP `cat ${SERVER_PID} | head -n 1` || rc_failed
        else
            rc_failed
        fi
        rc_status
        ;;
    restart)
        $0 stop && sleep 2 ; $0 start
        rc_status
        ;;
    force-restart)
        $0 force-stop && sleep 2 ; $0 start
        rc_status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|force-stop|restart|force-restart|reload}"
        exit 1
        ;;
esac

rc_exit

