#! /bin/sh
#
# Copyright (c) 2003,2004,2005,2006,2007,2012 init.at
#
#
# RedHat stuff
# chkconfig: 2345 79 21
# description: rrd-server
#
### BEGIN INIT INFO
# Provides:      rrd-server-collector
# Required-Start: $network logging-server meta-server
# Should-Start: mysql
# Required-Stop: $network logging-server meta-server
# Should-Stop: mysql
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description:   start rrd-server-collector
### END INIT INFO

export SYSTEMD_NO_WRAP="1"
if [ -f /etc/rc.status ] ; then
    . /etc/rc.status
else
    . /etc/rc.status_suse
fi
. /etc/init.d/ics_tools.sh

ACT_SERVER_TYPE=collector
SERVER_BIN=/opt/cluster/sbin/rrd-server-${ACT_SERVER_TYPE}.py
#STOP_SERVER_BIN=/usr/local/sbin/stop_rrd_server.py
SERVER_PID=/var/run/rrd-server/rrd-server-${ACT_SERVER_TYPE}.pid
PYTHON_BIN=/usr/bin/python-init
SERVER_ARGS=""
SERVER_USER="idrrd"
SERVER_GROUP="idg"
META_FILE="/var/lib/meta-server/rrd-server-${ACT_SERVER_TYPE}"

test -x ${SERVER_BIN} || exit 5
test -x ${PYTHON_BIN} || exit 5

rc_reset

id ${SERVER_USER} > /dev/null || { echo "User ${SERVER_USER} for ${SERVER_BIN} not found, exiting..." ; rc_failed 6 ; rc_exit ; }
[ "`id ${SERVER_USER} -g -n`" != "${SERVER_GROUP}" ] && { echo "Group ${SERVER_GROUP} for ${SERVER_BIN} not found, exiting..." ; rc_failed 6 ; rc_exit ; }

export HOSTNAME=`/bin/hostname`
case "$1" in
    start)
        echo -n "Starting rrd-server-${ACT_SERVER_TYPE}.py"
        if [ -f ${SERVER_PID} ] ; then
            echo -n " ... already running"
        else
            ${SERVER_BIN} ${SERVER_ARGS} -f -u ${SERVER_USER} -g ${SERVER_GROUP}
        fi
        rc_status -v
        ;;
    stop)
        echo -n "Stopping rrd-server-${ACT_SERVER_TYPE}.py ... "
        if [ -f ${SERVER_PID} ] ; then
            kill -s 15 `cat ${SERVER_PID} | head -n 1` || rc_failed
        else
            rc_failed
        fi
        rm -f ${SERVER_PID}
        rc_status -v
        ;;
    force-stop)
        echo -n "Force stopping rrd-server-${ACT_SERVER_TYPE}.py"
        if [ -f ${SERVER_PID} ] ; then
            kill -9 `cat ${SERVER_PID} ` || rc_failed
        else
            rc_failed
        fi
        rm -f ${SERVER_PID} ${META_FILE}
        rc_status -v
        ;;
    status)
        echo -n "Checking rrd-server-${ACT_SERVER_TYPE}.py..."
        check_threads_ok && {
            rc_status -v ; 
        } || {
            if ${SERVER_BIN} -C ; then
                check_threads || rc_failed 
                rc_status -v
            else
                rc_status -s
            fi
        } 
        ;;
    restart)
        $0 stop && sleep 2 ; $0 start
        rc_status
        ;;
    force-restart)
        $0 force-stop && sleep 2 ; $0 start
        rc_status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|force-stop|restart|force-restart}"
        exit 1
        ;;
esac

rc_exit

