# -*- coding: utf-8 -*-
#
# Copyright (C) 2015-2017 Bernhard Mallinger, Andreas Lang-Nevyjel
#
# Send feedback to: <mallinger@init.at>, <lang-nevyjel@init.at>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License Version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

from collections import namedtuple

from enum import Enum

# NOTE: This file has been automatically generated by generate_license_list.py
# DO NOT EDIT

__all__ = ['get_available_licenses', 'LicenseEnum', 'LicenseParameterTypeEnum']


def id_string_to_user_name(cls, id_string):
    try:
        return cls[id_string].to_user_name()
    except KeyError:
        return id_string

# NOTE: This file has been automatically generated by generate_license_list.py
# DO NOT EDIT


# NOTE: due to automatic generation, the values of this license enum may not be stable
# do not use them in the database, only their id string values

LicenseEnum = Enum('LicenseEnum', 'md_config_server kpi graphing discovery_server monitoring_dashboard distributed_monitoring snapshot notification network_weathermap rootkit_hunter reporting ext_license virtual_desktop hpc_workbench package_install rms netboot fast_frontend')
LicenseEnum.to_user_name = lambda x: dict((
    (LicenseEnum.md_config_server, 'MD Config Server'), 
    (LicenseEnum.kpi, 'Key Performance Indicators'), 
    (LicenseEnum.graphing, 'Graphing'), 
    (LicenseEnum.discovery_server, 'Discovery Server'), 
    (LicenseEnum.monitoring_dashboard, 'Monitoring Dashboard'), 
    (LicenseEnum.distributed_monitoring, 'Distributed Monitoring'), 
    (LicenseEnum.snapshot, 'Database Snapshot'), 
    (LicenseEnum.notification, 'Notifications'), 
    (LicenseEnum.network_weathermap, 'Network Weathermap'), 
    (LicenseEnum.rootkit_hunter, 'Rootkit Hunter'), 
    (LicenseEnum.reporting, 'Reporting'), 
    (LicenseEnum.ext_license, 'License Optimization Management'), 
    (LicenseEnum.virtual_desktop, 'Virtual Desktop'), 
    (LicenseEnum.hpc_workbench, 'HPC Workbench'), 
    (LicenseEnum.package_install, 'Package Install'), 
    (LicenseEnum.rms, 'Resource Management System'), 
    (LicenseEnum.netboot, 'Netboot'), 
    (LicenseEnum.fast_frontend, 'Allegro Webfrontend')
)).get(x, None)
LicenseEnum.id_string_to_user_name = classmethod(id_string_to_user_name)

# NOTE: This file has been automatically generated by generate_license_list.py
# DO NOT EDIT

LicenseParameterTypeEnum = Enum('LicenseParameterTypeEnum', 'service device user ext_license ovum')
LicenseParameterTypeEnum.to_user_name = lambda x: dict((
    (LicenseParameterTypeEnum.service, 'Service'), 
    (LicenseParameterTypeEnum.device, 'Device'), 
    (LicenseParameterTypeEnum.user, 'User'), 
    (LicenseParameterTypeEnum.ext_license, 'External license'), 
    (LicenseParameterTypeEnum.ovum, 'ICSW Egg')
)).get(x, None)
LicenseParameterTypeEnum.id_string_to_user_name = classmethod(id_string_to_user_name)

# NOTE: This file has been automatically generated by generate_license_list.py
# DO NOT EDIT


def get_available_licenses():
    from initat.cluster.backbone.models.license import InitProduct
    AvailableLicense = namedtuple('AvailableLicense', ['id', 'enum_value', 'name', 'description', 'product'])

    available_licenses = []

    available_licenses.append(
        AvailableLicense(
            id='md_config_server',
            enum_value=LicenseEnum.md_config_server,
            name='MD Config Server',
            description='Monitoring Daemon Configuration Writer',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='kpi',
            enum_value=LicenseEnum.kpi,
            name='Key Performance Indicators',
            description='Calculate key figures to measure the performance of your cluster',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='graphing',
            enum_value=LicenseEnum.graphing,
            name='Graphing',
            description='Comprehensive graphical evaluation using RRDs',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='discovery_server',
            enum_value=LicenseEnum.discovery_server,
            name='Discovery Server',
            description='Automatical configuration using SNMP',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='monitoring_dashboard',
            enum_value=LicenseEnum.monitoring_dashboard,
            name='Monitoring Dashboard',
            description='Central monitoring unit consisting of livestatus, geolocation and maplocation',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='distributed_monitoring',
            enum_value=LicenseEnum.distributed_monitoring,
            name='Distributed Monitoring',
            description='Distribute monitoring load to multiple workers',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='snapshot',
            enum_value=LicenseEnum.snapshot,
            name='Database Snapshot',
            description='Keep track of the configuration changes',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='notification',
            enum_value=LicenseEnum.notification,
            name='Notifications',
            description='Status notifications via mail and text messages',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='network_weathermap',
            enum_value=LicenseEnum.network_weathermap,
            name='Network Weathermap',
            description='Overview of relevant network utilization data',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='rootkit_hunter',
            enum_value=LicenseEnum.rootkit_hunter,
            name='Rootkit Hunter',
            description='Security scan for installations',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='reporting',
            enum_value=LicenseEnum.reporting,
            name='Reporting',
            description='Generate graphs to view the state of your cluster',
            product=InitProduct.NOCTUA,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='ext_license',
            enum_value=LicenseEnum.ext_license,
            name='License Optimization Management',
            description='Interactive graphic license utlilization evaluation',
            product=InitProduct.NESTOR,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='virtual_desktop',
            enum_value=LicenseEnum.virtual_desktop,
            name='Virtual Desktop',
            description='Manage virtual desktop sessions on your cluster',
            product=InitProduct.NESTOR,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='hpc_workbench',
            enum_value=LicenseEnum.hpc_workbench,
            name='HPC Workbench',
            description='Convenient interface for job management',
            product=InitProduct.NESTOR,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='package_install',
            enum_value=LicenseEnum.package_install,
            name='Package Install',
            description='Configure repositories and install packages on your nodes',
            product=InitProduct.NESTOR,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='rms',
            enum_value=LicenseEnum.rms,
            name='Resource Management System',
            description='Overview over your job system',
            product=InitProduct.NESTOR,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='netboot',
            enum_value=LicenseEnum.netboot,
            name='Netboot',
            description='Manage the boot process of your nodes',
            product=InitProduct.NESTOR,
        )
    )
    available_licenses.append(
        AvailableLicense(
            id='fast_frontend',
            enum_value=LicenseEnum.fast_frontend,
            name='Allegro Webfrontend',
            description='Transforms the Webfrontend into a super-fast single-page app',
            product=InitProduct.NOCTUA,
        )
    )

    return available_licenses
