# run this with `vagrant --up --provider=ovirt3`

Vagrant.configure('2') do |config|
  config.vm.box = 'ovirt'
  #config.vm.box_url = 'https://github.com/myoung34/vagrant-ovirt3/blob/master/example_box/dummy.box?raw=true'
  #config.vm.box_url = 'https://snowflakehosting.ch/vagrant/lxc-jessie-amd64.box'
  #config.vm.box_url = 'https://github.com/myoung34/vagrant-ovirt3/blob/master/example_box/dummy.box?raw=true'
  #config.vm.box_url = 'https://raw.github.com/pradels/vagrant-ovirt/master/example_box/ovirt.box'
  config.vm.box_url = 'https://github.com/myoung34/vagrant-ovirt3/blob/master/example_box/dummy.box?raw=true'

  config.vm.provider :ovirt3 do |ovirt|
    ovirt.template = 'VAGRANT_TEST_TEMPLATE_2'
    ovirt.cpus = 2
    ovirt.memory = 4092
    ovirt.console = 'vnc' #could also be 'spice'
    ovirt.url = 'https://ovirt-engine.init.at:443/ovirt-engine'
    ovirt.ca_no_verify = true
    ovirt.username = 'admin@internal'
    ovirt.password = 'ADD_PASSWORD_HERE'
    ovirt.datacenter = 'Default'
  end
end
