#! /bin/bash
#
# Copyright (c) 2001,2002,2003,2004,2005,2008,2012,2013 Andreas Lang-Nevyjel init.at
#
# RedHat stuff
# chkconfig: 2345 79 21
# description: mother
#
### BEGIN INIT INFO
# Provides:      mother
# Should-Start: logcheck-server mysql postgresql
# Required-Start: $network logging-server
# Required-Stop: $network logging-server logcheck-server
# Default-Start: 2 3 5
# Default-Stop: 0 1 6 
# Description:   start mother
### END INIT INFO

export SYSTEMD_NO_WRAP="1"
if [ -f /etc/rc.status ] ; then
    . /etc/rc.status
else
    . /etc/rc.status_suse
fi
# source /etc/sysconfig/mother
. /etc/sysconfig/mother
. /etc/init.d/ics_tools.sh

if [ -x /etc/init.d/syslog ] ; then
    SYSLOG_RC=/etc/init.d/syslog
else
    SYSLOG_RC=/etc/init.d/syslog-ng
fi

SERVER_BIN=/opt/cluster/sbin/mother.py
PYTHON_BIN=/usr/bin/python-init
SERVER_PID=/var/run/mother/mother.pid
SERVER_USER="idmother"
SERVER_GROUP="idg"
META_FILE="/var/lib/meta-server/mother"

test -x ${SERVER_BIN} || exit 5
test -x ${PYTHON_BIN} || exit 5

rc_reset

export HOSTNAME=`/bin/hostname`
case "$1" in
    start)
        #echo -n "Stopping syslog-ng"
        #${SYSLOG_RC} stop
        echo -n "Starting mother.py"
        if [ -f ${SERVER_PID} ] ; then
            echo -n " ... already running"
        else
            #${SERVER_BIN} ${SERVER_ARGS} -f -u ${SERVER_USER} -g ${SERVER_GROUP}
                # right now mother must have root-attributes in oder to use raw sockets (for pinging and stuff)
            ${SERVER_BIN} ${SERVER_ARGS}
        fi
        rc_status -v
        ;;
    stop)
        echo -n "Stopping mother.py"
        if [ -f ${SERVER_PID} ] ; then
            kill -s 15 `cat ${SERVER_PID} | head -n 1` 
            for i in $(seq 10) ; do
            [ ! -f ${SERVER_PID} ] && break
            echo -n "."
            sleep 2
            done
            [ $i -gt 8 ] && rc_failed
        else
            rc_failed
        fi
        rm -f ${SERVER_PID}
        rc_status -v
        ;;
    force-stop)
        echo -n "Force stopping mother.py"
        if [ -f ${SERVER_PID} ] ; then
            kill -9 `cat ${SERVER_PID} ` || rc_failed
        else
            rc_failed
        fi
        rm -f ${SERVER_PID} ${META_FILE}
        rc_status -v
        ;;
    status)
        echo -n "Checking mother.py..."
        check_threads_ok && {
            rc_status -v ; 
        } || {
            if ${SERVER_BIN} -C ; then
            check_threads || rc_failed 
            rc_status -v
            else
            rc_status -s
            fi
        } 
        ;;
    restart)
        echo "Restarting $(basename $SERVER_BIN)"
        $0 stop && sleep 2 ; $0 start || return=$rc_failed
        ;;
    force-restart)
        echo "Force-restarting $(basename $SERVER_BIN)"
        $0 force-stop && sleep 2 ; $0 start || return=$rc_failed
        ;;
    *)
        echo "Usage: $0 {start|stop|status|force-stop|restart|force-restart}"
        exit 1
        ;;
esac

rc_exit
