Document: host-monitoring
Title: Debian host-monitoring Manual
Author: <insert document author here>
Abstract: This manual describes what host-monitoring is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/host-monitoring/host-monitoring.sgml.gz

Format: postscript
Files: /usr/share/doc/host-monitoring/host-monitoring.ps.gz

Format: text
Files: /usr/share/doc/host-monitoring/host-monitoring.text.gz

Format: HTML
Index: /usr/share/doc/host-monitoring/html/index.html
Files: /usr/share/doc/host-monitoring/html/*.html
