#!/bin/bash

SERVICES="host-monitoring host-relay snmp-relay"
FILES="/tmp/.restart_host_monitoring /tmp/.restart_host_relay /tmp/.restart_snmp_relay"

for file in $FILES; do
    rm -rf $file
done

for service in $SERVICES; do
    update-rc.d $service disable
    update-rc.d -f $service remove
done

