#!/bin/sh
#
# Copyright (c) 2012 Andreas Lang-Nevyjel, lang-nevyjel@init.at
#
### BEGIN INIT INFO
# Provides:      host-monitoring
# Required-Start: $network $syslog logging-server
# Required-Stop: $network $syslog logging-server
# Should-Start: 
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description:   start FCGI-tasks of webfrontend
### END INIT INFO

export SYSTEMD_NO_WRAP="1"
if [ -f /etc/rc.status ] ; then
    . /etc/rc.status
else
    . /etc/rc.status_suse
fi

PID_FILE=/var/run/django.webfrontend.pid
LOG_FILE=/var/log/webfrontend.log
rc_reset

case "$1" in
    start)
        echo "Starting webfrontend"

        cd /opt/python-init/lib/python/site-packages/init/cluster/
        export OEKOTEX_INI=olim.ini
        python-init manage.py runfcgi host=127.0.0.1 port=9002 method=prefork maxrequests=64 daemonize=true maxspare=16 pidfile=${PID_FILE} outlog=${LOG_FILE}
    
        /etc/init.d/nginx restart
    
        rc_status -v
    
        ;;
    stop)
    
        echo "Shutting down webfrontend"
        kill $(cat ${PID_FILE})
    
        rc_status -v
        ;;
    restart)
        $0 stop
        sleep 2
        $0 start
    
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

rc_exit

