# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0896_netdevice_ignore_netdevice_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='categories',
            field=models.ManyToManyField(blank=True, to='backbone.category'),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_device_type',
            field=models.ManyToManyField(blank=True, to='backbone.network_device_type'),
        ),
    ]
