# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0898_auto_20160107_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csw_permission',
            options={'ordering': ('content_type__app_label', 'content_type__model', 'name'), 'verbose_name': 'Global permission'},
        ),
        migrations.AddField(
            model_name='category',
            name='useable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='alias',
            field=models.CharField(blank=True, default=b'', max_length=384),
        ),
        migrations.AlterField(
            model_name='device',
            name='comment',
            field=models.CharField(blank=True, default=b'', max_length=384),
        ),
        migrations.AlterField(
            model_name='device_group',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=384),
        ),
        migrations.AlterField(
            model_name='deviceselection',
            name='categories',
            field=models.ManyToManyField(blank=True, to='backbone.category'),
        ),
        migrations.AlterField(
            model_name='deviceselection',
            name='device_groups',
            field=models.ManyToManyField(blank=True, to='backbone.device_group'),
        ),
        migrations.AlterField(
            model_name='deviceselection',
            name='devices',
            field=models.ManyToManyField(blank=True, to='backbone.device'),
        ),
    ]
