# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0899_auto_20160325_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherSetting',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default=b'', max_length=256)),
                ('is_system', models.BooleanField(default=False)),
                ('mult', models.IntegerField(default=1)),
                ('sched_start_second', models.IntegerField(default=None, null=True)),
                ('sched_start_minute', models.IntegerField(default=None, null=True)),
                ('sched_start_hour', models.IntegerField(default=None, null=True)),
                ('sched_start_day', models.IntegerField(default=None, null=True)),
                ('sched_start_week', models.IntegerField(default=None, null=True)),
                ('sched_start_month', models.IntegerField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('com_capabilities', models.ManyToManyField(to='backbone.ComCapability')),
            ],
        ),
        migrations.CreateModel(
            name='DispatcherSettingSchedule',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=64, unique=True)),
                ('baseline', models.IntegerField(choices=[(0, b'year'), (1, b'month'), (2, b'week'), (3, b'day'), (4, b'hour'), (5, b'minute'), (6, b'second')])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='monitoring_hint',
            name='value_blob',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='sensorthreshold',
            name='notify_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchersetting',
            name='run_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.DispatcherSettingSchedule'),
        ),
        migrations.AddField(
            model_name='dispatchersetting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
