# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0899_auto_20160325_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, b'PACKAGE'), (2, b'HARDWARE'), (3, b'LICENSE'), (4, b'UPDATE'), (5, b'SOFTWARE_VERSION')])),
                ('value', models.BinaryField()),
                ('name', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='AssetBatch',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRun',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('run_index', models.IntegerField(default=1)),
                ('run_status', models.IntegerField(choices=[(1, b'PLANNED'), (2, b'RUNNING'), (3, b'ENDED')], null=True)),
                ('run_start_time', models.DateTimeField(blank=True, null=True)),
                ('run_end_time', models.DateTimeField(blank=True, null=True)),
                ('asset_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.AssetBatch')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.device')),
            ],
        ),
        migrations.AlterField(
            model_name='monitoring_hint',
            name='value_blob',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='sensorthreshold',
            name='notify_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.AssetRun'),
        ),
    ]
