# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0900_auto_20160421_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrun',
            name='raw_result_interpreted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetrun',
            name='raw_result_str',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='assetrun',
            name='run_type',
            field=models.IntegerField(choices=[(1, b'PACKAGE'), (2, b'HARDWARE'), (3, b'LICENSE'), (4, b'UPDATE'), (5, b'SOFTWARE_VERSION')], null=True),
        ),
    ]
