# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0901_auto_20160422_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assetrun',
            name='raw_result_str',
            field=models.TextField(null=True),
        ),
    ]
