# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0905_auto_20160426_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchsetting',
            name='source',
            field=models.IntegerField(choices=[(1, b'SNMP'), (2, b'ASU'), (3, b'IPMI'), (4, b'NRPE_PACKAGE'), (5, b'NRPE_HARDWARE'), (6, b'NRPE_LICENSE'), (7, b'NRPE_UPDATE'), (8, b'NRPE_SOFTWARE_VERSION'), (9, b'NRPE_PROCESS')]),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='source',
            field=models.IntegerField(choices=[(1, b'SNMP'), (2, b'ASU'), (3, b'IPMI'), (4, b'NRPE_PACKAGE'), (5, b'NRPE_HARDWARE'), (6, b'NRPE_LICENSE'), (7, b'NRPE_UPDATE'), (8, b'NRPE_SOFTWARE_VERSION'), (9, b'NRPE_PROCESS')]),
        ),
    ]
