# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0906_auto_20160426_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrun',
            name='scan_type',
            field=models.IntegerField(choices=[(1, b'HM'), (2, b'NRPE')], null=True),
        ),
    ]
