# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0909_auto_20160428_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPackage',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('version', models.TextField(blank=True, null=True)),
                ('release', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='assetrun',
            name='packages',
            field=models.ManyToManyField(to='backbone.AssetPackage'),
        ),
    ]
