# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0900_auto_20160504_1141'),
        ('backbone', '0911_auto_20160504_1131'),
    ]

    operations = [
    ]
