# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0911_auto_20160504_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDispatcherLink',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.device')),
                ('dispatcher_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.DispatcherSetting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
