# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0913_auto_20160504_1216'),
        ('backbone', '0912_devicedispatcherlink'),
    ]

    operations = [
    ]
