# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0915_scheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='run_now',
            field=models.BooleanField(default=False),
        ),
    ]
