# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0917_auto_20160510_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpackageversion',
            name='name',
        ),
    ]
