# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0918_remove_assetpackageversion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrun',
            name='packages',
            field=models.ManyToManyField(to='backbone.AssetPackageVersion'),
        ),
    ]
