# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0919_auto_20160510_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='dispatch_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.DispatcherSetting'),
        ),
    ]
