# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0920_scheduleitem_dispatch_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpackage',
            name='package_type',
            field=models.IntegerField(choices=[(1, b'WINDOWS'), (2, b'LINUX')], default=1),
            preserve_default=False,
        ),
    ]
