# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0921_assetpackage_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrun',
            name='run_status',
            field=models.IntegerField(choices=[(1, b'PLANNED'), (2, b'RUNNING'), (3, b'ENDED'), (4, b'FAILED')], null=True),
        ),
    ]
