# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0922_auto_20160517_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrun',
            name='run_duration',
            field=models.IntegerField(default=0),
        ),
    ]
