# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0923_assetrun_run_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.device'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='num_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='num_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='num_runs_error',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='num_runs_ok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='run_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='run_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='run_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetrun',
            name='batch_index',
            field=models.IntegerField(default=0),
        ),
    ]
