# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0925_insert_asset_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrun',
            name='run_result',
            field=models.IntegerField(choices=[(1, b'UNKNOWN'), (2, b'SUCCESS'), (3, b'WARNING'), (4, b'FAILED')], default=1),
        ),
        migrations.AlterField(
            model_name='assetrun',
            name='run_status',
            field=models.IntegerField(choices=[(1, b'PLANNED'), (2, b'RUNNING'), (3, b'ENDED'), (4, b'FAILED')], default=1),
        ),
        migrations.AlterField(
            model_name='assetrun',
            name='run_type',
            field=models.IntegerField(choices=[(1, b'PACKAGE'), (2, b'HARDWARE'), (3, b'LICENSE'), (4, b'UPDATE'), (5, b'SOFTWARE_VERSION'), (6, b'PROCESS'), (7, b'PENDING_UPDATE')], default=1),
        ),
    ]
