# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 05:20
from __future__ import unicode_literals

from django.db import migrations, models


def fix_run_status(apps, schema_editor):
    # fix run stati
    asset_run = apps.get_model("backbone", "AssetRun")
    for _run in asset_run.objects.all():
        _changed = False
        if _run.run_status > 3:
            _run.run_status = 3
            _run.run_result = 4
            _run.save()


def dummy_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    reversible = True

    dependencies = [
        ('backbone', '0926_auto_20160521_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrun',
            name='run_status',
            field=models.IntegerField(choices=[(1, b'PLANNED'), (2, b'RUNNING'), (3, b'ENDED')], default=1),
        ),
        migrations.RunPython(fix_run_status, reverse_code=dummy_reverse)
    ]
