# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0927_remove_old_run_stati'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpackageversion',
            name='info',
            field=models.TextField(default=b''),
        ),
    ]
