# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0928_assetpackageversion_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='error_string',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='run_result',
            field=models.IntegerField(choices=[(1, b'UNKNOWN'), (2, b'SUCCESS'), (3, b'WARNING'), (4, b'FAILED'), (5, b'CANCELED')], default=1),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='run_status',
            field=models.IntegerField(choices=[(1, b'PLANNED'), (2, b'RUNNING'), (3, b'ENDED')], default=1),
        ),
        migrations.AlterField(
            model_name='assetrun',
            name='run_result',
            field=models.IntegerField(choices=[(1, b'UNKNOWN'), (2, b'SUCCESS'), (3, b'WARNING'), (4, b'FAILED'), (5, b'CANCELED')], default=1),
        ),
    ]
