# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0929_auto_20160523_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrun',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 23, 5, 49, 35, 542592, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
