# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 06:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0930_assetrun_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 23, 6, 5, 4, 604067, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
