# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0936_auto_20160523_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticassettemplate',
            name='description',
            field=models.TextField(default=b''),
        ),
    ]
