# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0939_assetlicenseentry_assetupdateentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrun',
            name='error_string',
            field=models.TextField(default=b''),
        ),
    ]
