# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0940_assetrun_error_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetupdateentry',
            name='new_version',
            field=models.CharField(default=b'', max_length=64),
        ),
    ]
