# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0942_assetrun_interpret_error_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPCIEntry',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.IntegerField(default=0)),
                ('bus', models.IntegerField(default=0)),
                ('slot', models.IntegerField(default=0)),
                ('func', models.IntegerField(default=0)),
                ('pci_class', models.IntegerField(default=0)),
                ('subclass', models.IntegerField(default=0)),
                ('device', models.IntegerField(default=0)),
                ('vendor', models.IntegerField(default=0)),
                ('revision', models.IntegerField(default=0)),
                ('pci_classname', models.CharField(default=b'', max_length=255)),
                ('subclassname', models.CharField(default=b'', max_length=255)),
                ('devicename', models.CharField(default=b'', max_length=255)),
                ('vendorname', models.CharField(default=b'', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('domain', 'bus', 'slot', 'func'),
            },
        ),
        migrations.AlterField(
            model_name='assetrun',
            name='run_type',
            field=models.IntegerField(choices=[(1, b'PACKAGE'), (2, b'HARDWARE'), (3, b'LICENSE'), (4, b'UPDATE'), (5, b'SOFTWARE_VERSION'), (6, b'PROCESS'), (7, b'PENDING_UPDATE'), (8, b'DMI'), (9, b'PCI')], default=1),
        ),
        migrations.AddField(
            model_name='assetpcientry',
            name='asset_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.AssetRun'),
        ),
    ]
