# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0943_auto_20160526_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDMIHandle',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('handle', models.IntegerField(default=0)),
                ('dmi_type', models.IntegerField(default=0)),
                ('header', models.CharField(default=b'', max_length=128)),
                ('length', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetDMIHead',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(default=b'', max_length=63)),
                ('size', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('asset_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.AssetRun')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDMIValue',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default=b'', max_length=128)),
                ('single_value', models.BooleanField(default=True)),
                ('num_values', models.IntegerField(default=1)),
                ('value', models.TextField(default=b'')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dmihandle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.AssetDMIHandle')),
            ],
        ),
        migrations.AddField(
            model_name='assetdmihandle',
            name='dmihead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.AssetDMIHead'),
        ),
    ]
