# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0945_csw_permission_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_variable',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_variable',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_variable',
            name='json_value',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='user_variable',
            name='var_type',
            field=models.CharField(choices=[(b's', b'string'), (b'i', b'integer'), (b'b', b'boolean'), (b'j', b'json-encoded'), (b'n', b'none')], max_length=2),
        ),
    ]
