# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0947_auto_20160529_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHWCPUEntry',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHWMemoryEntry',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assetrun',
            name='run_type',
            field=models.IntegerField(choices=[(1, b'PACKAGE'), (2, b'HARDWARE'), (3, b'LICENSE'), (4, b'UPDATE'), (5, b'SOFTWARE_VERSION'), (6, b'PROCESS'), (7, b'PENDING_UPDATE'), (8, b'DMI'), (9, b'PCI'), (10, b'PRETTYWINHW')], default=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='categories',
            field=models.ManyToManyField(blank=True, to='backbone.category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='stage1_flavour',
            field=models.CharField(blank=True, default=b'cpio', max_length=48),
        ),
        migrations.AddField(
            model_name='assethwmemoryentry',
            name='asset_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.AssetRun'),
        ),
        migrations.AddField(
            model_name='assethwcpuentry',
            name='asset_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.AssetRun'),
        ),
    ]
