# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0948_auto_20160603_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assethwcpuentry',
            name='asset_run',
        ),
        migrations.RemoveField(
            model_name='assethwcpuentry',
            name='value',
        ),
        migrations.RemoveField(
            model_name='assethwmemoryentry',
            name='asset_run',
        ),
        migrations.RemoveField(
            model_name='assethwmemoryentry',
            name='value',
        ),
        migrations.AddField(
            model_name='assethwcpuentry',
            name='cpuname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assethwcpuentry',
            name='numberofcores',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assethwmemoryentry',
            name='banklabel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assethwmemoryentry',
            name='capacity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assethwmemoryentry',
            name='formfactor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assethwmemoryentry',
            name='manufacturer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assethwmemoryentry',
            name='memorytype',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assetrun',
            name='cpus',
            field=models.ManyToManyField(to='backbone.AssetHWCPUEntry'),
        ),
        migrations.AddField(
            model_name='assetrun',
            name='memory_modules',
            field=models.ManyToManyField(to='backbone.AssetHWMemoryEntry'),
        ),
    ]
