# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0949_auto_20160606_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrun',
            name='cpu_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetrun',
            name='memory_count',
            field=models.IntegerField(default=0),
        ),
    ]
