# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0950_auto_20160606_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, default=b'', max_length=16),
        ),
    ]
