# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0950_auto_20160606_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHWDisplayEntry',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('xpixels', models.IntegerField(null=True)),
                ('ypixels', models.IntegerField(null=True)),
                ('manufacturer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHWGPUEntry',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('gpuname', models.TextField(null=True)),
                ('driverversion', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHWHDDEntry',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('serialnumber', models.TextField(null=True)),
                ('size', models.BigIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHWLogicalEntry',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('size', models.BigIntegerField(null=True)),
                ('free', models.BigIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='assetrun',
            name='displays',
            field=models.ManyToManyField(to='backbone.AssetHWDisplayEntry'),
        ),
        migrations.AddField(
            model_name='assetrun',
            name='gpus',
            field=models.ManyToManyField(to='backbone.AssetHWGPUEntry'),
        ),
        migrations.AddField(
            model_name='assetrun',
            name='hdds',
            field=models.ManyToManyField(to='backbone.AssetHWHDDEntry'),
        ),
        migrations.AddField(
            model_name='assetrun',
            name='partitions',
            field=models.ManyToManyField(to='backbone.AssetHWLogicalEntry'),
        ),
    ]
