# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0951_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_counter',
            field=models.BigIntegerField(default=0),
        ),
    ]
