# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0951_auto_20160607_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp_counter_increase',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 7, 14, 20, 51, 142290, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='otp_counter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, default=b'', max_length=16),
        ),
    ]
