# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0952_user_otp_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp_counter_increase',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 7, 7, 16, 25, 426463, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
