# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0954_devicescanlock_run_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='active_scan',
        ),
    ]
