# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 17:37
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


def add_device_variable_uuids(apps, schema_editor):
    device_variable = apps.get_model("backbone", "device_variable")
    for entry in device_variable.objects.all():
        # create uuid (signals not working here)
        entry.prefix = "normal"
        entry.uuid = str(uuid.uuid4())
        entry.save()


def dummy_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0955_remove_device_active_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_variable',
            name='uuid',
            field=models.TextField(default=b'', max_length=64),
        ),
        migrations.AddField(
            model_name='device_variable',
            name='prefix',
            field=models.CharField(choices=[(b'normal', b'normal'), (b'inventar', b'inventar')], default=b'', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='device_variable',
            unique_together=set([('name', 'device', 'prefix')]),
        ),
        migrations.RunPython(add_device_variable_uuids, reverse_code=dummy_reverse)
    ]
