# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 13:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0955_remove_device_active_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_theme_selection',
            field=models.IntegerField(choices=[(1, b'default'), (2, b'init')], default=1),
        ),
    ]
