# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 05:14


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0957_create_devicevar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_variable',
            name='device_variable_scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.device_variable_scope'),
        ),
    ]
