# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_default_variable_scope(apps, schema_editor):
    device_variable_scope = apps.get_model("backbone", "device_variable_scope")
    for _scope in device_variable_scope.objects.all():
        _scope.default_scope = False
        _scope.save()

    _normal = device_variable_scope.objects.get(name="normal")
    _normal.default_scope = True
    _normal.save()


def dummy_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0958_auto_20160714_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='dvs_allowed_names',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=127, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='device_variable_scope',
            name='default_scope',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dvs_allowed_names',
            name='device_variable_scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.device_variable_scope'),
        ),
        migrations.RunPython(set_default_variable_scope, reverse_code=dummy_reverse),
    ]
