# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 14:38


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0956_user_ui_theme_selection'),
        ('backbone', '0959_auto_20160714_0926'),
    ]

    operations = [
    ]
