# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0962_auto_20160718_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvs_allowed_names',
            name='forced_type',
            field=models.CharField(choices=[(b'', b'ignore'), (b'i', b'integer'), (b's', b'string'), (b'd', b'datetime'), (b't', b'time'), (b'b', b'blob'), (b'?', b'guess')], default=b'', max_length=3),
        ),
        migrations.AddField(
            model_name='dvs_allowed_names',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
