# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0962_auto_20160718_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvs_allowed_names',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dvs_allowed_names',
            name='unique_per_device',
            field=models.BooleanField(default=False),
        ),
    ]
