# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 05:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0963_auto_20160718_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvs_allowed_names',
            name='group',
            field=models.CharField(default=b'', max_length=127),
        ),
    ]
