# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0964_dvs_allowed_names_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_variable',
            name='var_type',
            field=models.CharField(choices=[(b'i', b'integer'), (b's', b'string'), (b'd', b'datetime'), (b'D', b'date'), (b't', b'time'), (b'b', b'blob'), (b'?', b'guess')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dvs_allowed_names',
            name='forced_type',
            field=models.CharField(choices=[(b'', b'ignore'), (b'i', b'integer'), (b's', b'string'), (b'd', b'datetime'), (b'D', b'date'), (b't', b'time'), (b'b', b'blob')], default=b'', max_length=3),
        ),
        migrations.AlterField(
            model_name='staticassettemplatefield',
            name='field_description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
