# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0966_auto_20160720_1232_squashed_0967_staticassettemplate_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='asset',
            field=models.BooleanField(default=False),
        ),
    ]
