# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 11:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0966_auto_20160720_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticassettemplate',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
