# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0968_staticassettemplatefield_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceClass',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=64, unique=True)),
                ('description', models.CharField(default=b'', max_length=128)),
                ('limitations', models.TextField(default=b'')),
                ('system_class', models.BooleanField(default=False)),
                ('default_system_class', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.DeviceClass'),
        ),
    ]
