# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0969_deviceclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.DeviceClass'),
        ),
    ]
