# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0970_auto_20160728_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticassetfieldvalue',
            old_name='user',
            new_name='change_user',
        ),
        migrations.AddField(
            model_name='staticasset',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
