# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 07:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0971_auto_20160808_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticassettemplatefield',
            name='show_in_overview',
            field=models.BooleanField(default=False),
        ),
    ]
