# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0972_staticassettemplatefield_show_in_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticassettemplatefield',
            name='consumable_critical_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staticassettemplatefield',
            name='consumable_start_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staticassettemplatefield',
            name='consumable_warn_value',
            field=models.IntegerField(default=0),
        ),
    ]
