# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 14:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0973_auto_20160809_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticassetfieldvalue',
            name='value_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='staticassettemplatefield',
            name='default_value_text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='staticassettemplatefield',
            name='field_type',
            field=models.IntegerField(choices=[(1, b'INTEGER'), (2, b'STRING'), (3, b'DATE'), (4, b'TEXT')]),
        ),
    ]
