# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0975_auto_20160811_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticassettemplatefield',
            name='date_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staticassettemplatefield',
            name='date_critical_value',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='staticassettemplatefield',
            name='date_warn_value',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='staticassettemplatefield',
            name='default_value_text',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
