# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 18:43


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0976_auto_20160811_0949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dvs_allowed_names',
            new_name='dvs_allowed_name',
        ),
    ]
