# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0977_auto_20160811_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_variable',
            name='dvs_allowed_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.dvs_allowed_name'),
        ),
    ]
