# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 16:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0978_device_variable_dvs_allowed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_variable_scope',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='dvs_allowed_name',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dvs_allowed_name',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='dvs_allowed_name',
            name='group',
            field=models.CharField(blank=True, default=b'', max_length=127),
        ),
    ]
