# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0979_auto_20160812_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_variable_scope',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
