# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0980_device_variable_scope_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=64, unique=True)),
                ('description', models.TextField(default=b'')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RoleObjectPermission',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('csw_object_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.csw_object_permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.Role')),
            ],
            options={
                'verbose_name': 'Global Ooject permissions of Role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('csw_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.csw_permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.Role')),
            ],
            options={
                'verbose_name': 'Global permissions of Role',
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='object_permissions',
        ),
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='object_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='object_perms',
            field=models.ManyToManyField(blank=True, related_name='role_perms', through='backbone.RoleObjectPermission', to='backbone.csw_object_permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='perms',
            field=models.ManyToManyField(blank=True, related_name='role_perms', through='backbone.RolePermission', to='backbone.csw_permission'),
        ),
        migrations.AddField(
            model_name='group',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='role_groups', to='backbone.Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='role_users', to='backbone.Role'),
        ),
    ]
