# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0981_auto_20160824_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
