# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0983_role_based_scheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleobjectpermission',
            options={'verbose_name': 'Global Object permissions of Role'},
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='cpu_count',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='cpus',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='displays',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='gpus',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='hdds',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='memory_count',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='memory_modules',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='partitions',
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='cpus',
            field=models.ManyToManyField(to='backbone.AssetHWCPUEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='displays',
            field=models.ManyToManyField(to='backbone.AssetHWDisplayEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='gpus',
            field=models.ManyToManyField(to='backbone.AssetHWGPUEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='hdds',
            field=models.ManyToManyField(to='backbone.AssetHWHDDEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='memory_modules',
            field=models.ManyToManyField(to='backbone.AssetHWMemoryEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='packages',
            field=models.ManyToManyField(to='backbone.AssetPackageVersion'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='partitions',
            field=models.ManyToManyField(to='backbone.AssetHWLogicalEntry'),
        ),
        migrations.AlterField(
            model_name='assetrun',
            name='run_type',
            field=models.IntegerField(choices=[(1, b'PACKAGE'), (2, b'HARDWARE'), (3, b'LICENSE'), (4, b'UPDATE'), (5, b'LSHW'), (6, b'PROCESS'), (7, b'PENDING_UPDATE'), (8, b'DMI'), (9, b'PCI'), (10, b'PRETTYWINHW')], default=1),
        ),
    ]
