# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0983_auto_20160825_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrun',
            name='cpu_count',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='cpus',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='displays',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='gpus',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='hdds',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='memory_count',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='memory_modules',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='partitions',
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='cpus',
            field=models.ManyToManyField(to='backbone.AssetHWCPUEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='displays',
            field=models.ManyToManyField(to='backbone.AssetHWDisplayEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='gpus',
            field=models.ManyToManyField(to='backbone.AssetHWGPUEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='hdds',
            field=models.ManyToManyField(to='backbone.AssetHWHDDEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='memory_modules',
            field=models.ManyToManyField(to='backbone.AssetHWMemoryEntry'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='packages',
            field=models.ManyToManyField(to='backbone.AssetPackageVersion'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='partitions',
            field=models.ManyToManyField(to='backbone.AssetHWLogicalEntry'),
        ),
    ]
