# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:23


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0984_auto_20160830_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrun',
            name='device',
        ),
    ]
