# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 05:55


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0985_auto_20161018_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='md_cache_mode',
        ),
    ]
