# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0986_auto_20160901_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpackageversioninstalltime',
            name='install_time',
        ),
        migrations.RemoveField(
            model_name='assetrun',
            name='packages_install_times',
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='packages_install_times',
            field=models.ManyToManyField(to='backbone.AssetPackageVersionInstallTime'),
        ),
        migrations.AddField(
            model_name='assetpackageversioninstalltime',
            name='timestamp',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
