# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0986_remove_device_md_cache_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='monhosttracegeneration',
            name='edges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monhosttracegeneration',
            name='nodes',
            field=models.IntegerField(default=0),
        ),
    ]
