# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 07:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0987_auto_20160902_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
