# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0987_auto_20160902_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
