# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:05


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0988_staticassettemplate_multi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='bz2_capable',
        ),
        migrations.RemoveField(
            model_name='device',
            name='propagation_level',
        ),
        migrations.RemoveField(
            model_name='device',
            name='show_in_bootcontrol',
        ),
        migrations.AddField(
            model_name='device',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
