# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 08:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0988_reporthistory_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
