# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0990_auto_20160905_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetbatch',
            name='hdds',
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='partition_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.partition_table'),
        ),
    ]
