# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0991_auto_20160905_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalDisc',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=128)),
                ('size', models.BigIntegerField(null=True)),
                ('free_space', models.BigIntegerField(null=True)),
                ('partition_fs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.partition_fs')),
                ('partitions', models.ManyToManyField(to='backbone.partition')),
            ],
        ),
    ]
