# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0991_device_variable_scope_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_variable_scope',
            name='system_scope',
            field=models.BooleanField(default=False),
        ),
    ]
