# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0992_device_variable_scope_system_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_variable_scope',
            name='forced_flags',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='device_variable_scope',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AlterUniqueTogether(
            name='dvs_allowed_name',
            unique_together=set([('name', 'device_variable_scope')]),
        ),
    ]
