# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 08:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0993_auto_20160912_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='configserviceenum',
            name='root_service',
            field=models.BooleanField(default=True),
        ),
    ]
