# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0993_auto_20161106_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvs_allowed_name',
            name='name',
            field=models.CharField(default='', max_length=127),
        ),
    ]
