# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0994_configserviceenum_root_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='system_config',
        ),
        migrations.AddField(
            model_name='config_catalog',
            name='priorty',
            field=models.IntegerField(default=0),
        ),
    ]
