# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 12:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0995_auto_20161111_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_variable',
            name='val_bool',
            field=models.NullBooleanField(default=False),
        ),
    ]
