# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 21:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0996_device_variable_val_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dynamic_checks',
            field=models.BooleanField(default=False),
        ),
    ]
