# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 12:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0996_auto_20160913_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='file_hash',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='hash_algorithm',
            field=models.TextField(null=True),
        ),
    ]
