# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0998_mondisplaypipespec'),
    ]

    operations = [
        migrations.AddField(
            model_name='mondisplaypipespec',
            name='def_user_var_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
