# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 09:50


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0998_auto_20160915_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mon_dist_master',
            name='md_version',
        ),
    ]
