# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0999_remove_mon_dist_master_md_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareFingerPrint',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('fingerprint', models.TextField(default=b'')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.device')),
            ],
        ),
    ]
