# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:53


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1000_auto_20161128_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedService',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default domain', max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistributedServiceNode',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('is_domain_node', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.device_config')),
                ('domaindefinition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.DistributedService')),
            ],
        ),
        migrations.CreateModel(
            name='DomainTypeEnum',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('enum_name', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('info', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('default_enum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dte_default', to='backbone.ConfigServiceEnum')),
                ('domain_enum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dte_domain', to='backbone.ConfigServiceEnum')),
            ],
        ),
        migrations.AlterField(
            model_name='devicelogentry',
            name='entry_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mondisplaypipespec',
            name='def_user_var_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='distributedservice',
            name='domaintypeenum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backbone.DomainTypeEnum'),
        ),
    ]
