# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1000_hardwarefingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarefingerprint',
            name='changecount',
            field=models.IntegerField(default=1),
        ),
    ]
