# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 08:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1001_auto_20161128_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelogentry',
            name='entry_counter',
        ),
    ]
