# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 08:17
from __future__ import unicode_literals

from django.db import migrations

def fix_assetbatch_and_assetrun(apps, schema_editor):
    AssetBatch = apps.get_model("backbone", "AssetBatch")
    AssetRun = apps.get_model("backbone", "AssetRun")

    for ab in AssetBatch.objects.all():
        ab.run_status = 5
        ab.save()
    
    for ar in AssetRun.objects.all():
        ar.run_status = 5
        ar.save() 

class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1003_auto_20160927_0907'),
    ]

    operations = [
        migrations.RunPython(fix_assetbatch_and_assetrun)
    ]
