# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1003_auto_20161130_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedispatcherlink',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicedispatcherlink',
            name='dispatcher_setting',
        ),
        migrations.RemoveField(
            model_name='devicedispatcherlink',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='device',
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='schedule_handler',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='DeviceDispatcherLink',
        ),
    ]
