# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:24


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1004_auto_20160927_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetHWHDDEntry',
        ),
    ]
