# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1005_auto_20161201_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapScan',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('raw_result', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.network')),
            ],
        ),
    ]
