# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 06:52


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1005_delete_assethwhddentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assethwcpuentry',
            old_name='cpuname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='assethwgpuentry',
            old_name='gpuname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='assethwgpuentry',
            name='driverversion',
        ),
    ]
