# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1006_nmapscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='rms_user',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('fshare', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('default_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.rms_project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rms_job',
            name='rms_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backbone.rms_user'),
        ),
    ]
