# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1006_auto_20160929_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition_disc',
            name='serial',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='partition_disc',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
