# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:37


from django.db import migrations, models

def rename_staticassettemplate_type(apps, schema_editor):
    StaticAssetTemplate = apps.get_model("backbone", "StaticAssetTemplate")

    for static_asset_template in StaticAssetTemplate.objects.all():
        if int(static_asset_template.type) == 1:
            static_asset_template.type = "License"
        elif int(static_asset_template.type) == 2:
            static_asset_template.type = "Contract"
        elif int(static_asset_template.type) == 3:
            static_asset_template.type = "Hardware"

        static_asset_template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1007_auto_20160929_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticassettemplate',
            name='type',
            field=models.CharField(max_length=256),
        ),
        migrations.RunPython(rename_staticassettemplate_type)
    ]
