# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 07:10


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1007_auto_20161202_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='rms_accounting_record',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('slots_used', models.IntegerField(default=0)),
                ('aggregation_level', models.CharField(choices=[('d', b'day'), ('h', b'hour'), ('n', b'none')], default='n', max_length=1)),
                ('aggregation_start', models.DateTimeField(default=None, null=True)),
                ('aggregation_end', models.DateTimeField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rms_accounting_run',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='rms_accounting_record',
            name='rms_accounting_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.rms_accounting_run'),
        ),
        migrations.AddField(
            model_name='rms_accounting_record',
            name='rms_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.rms_user'),
        ),
    ]
