# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 12:57
from __future__ import unicode_literals

from django.db import migrations

def fix_noneditable_dvs_scopes(apps, schema_editor):
    dvs_allowed_name = apps.get_model("backbone", "dvs_allowed_name")

    for dvs in dvs_allowed_name.objects.all():
        if dvs.device_variable_scope.name == "inventory":
            dvs.editable = True
            dvs.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1008_auto_20160929_1537'),
    ]

    operations = [
        migrations.RunPython(fix_noneditable_dvs_scopes)
    ]
