# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1010_auto_20161203_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='rms_accounting_run',
            name='slots_defined',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rms_accounting_run',
            name='aggregation_level',
            field=models.CharField(choices=[('n', b'none'), ('h', b'hour'), ('d', b'day'), ('m', b'month'), ('y', b'year')], default='n', max_length=1),
        ),
    ]
