# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1010_auto_20161002_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='icsweggconsumer',
            name='consumed',
            field=models.IntegerField(default=0),
        ),
    ]
