# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1011_auto_20161203_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='rms_accounting_run',
            name='num_source_records',
            field=models.IntegerField(default=0),
        ),
    ]
