# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1011_icsweggconsumer_consumed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('idx',), 'verbose_name': 'License'},
        ),
    ]
