# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 11:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1012_rms_accounting_run_num_source_records'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rmsjobvariable',
            unique_together=set([('name', 'rms_job', 'rms_job_run')]),
        ),
    ]
