# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 12:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1013_auto_20161205_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethwnetworkdevice',
            name='speed',
            field=models.BigIntegerField(null=True),
        ),
    ]
