# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 17:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1014_auto_20161004_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='icsweggconsumer',
            name='timeframe_secs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icsweggrequest',
            name='valid_until',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
