# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1015_remove_user_ui_theme_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicaldisc',
            name='mountpoint',
            field=models.CharField(blank=True, default='/', max_length=192),
        ),
    ]
