# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 13:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1016_auto_20161010_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon_dist_master',
            name='full_build',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mon_dist_slave',
            name='full_build',
            field=models.BooleanField(default=True),
        ),
    ]
