# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1017_auto_20161010_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetHWLogicalEntry',
        ),
    ]
