# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1016_logicaldisc_mountpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapScanIgnoredDevice',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=17, unique=True)),
            ],
        ),
    ]
