# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 09:02


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1017_nmapscanignoreddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelogentry',
            name='read_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_device_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
