# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 15:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1017_delete_assethwlogicalentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assethwdisplayentry',
            name='type',
        ),
    ]
