# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 11:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1020_auto_20170108_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring_hint',
            name='changed',
        ),
        migrations.AlterField(
            model_name='monitoring_hint',
            name='v_type',
            field=models.CharField(choices=[('f', 'float'), ('i', 'integer'), ('b', 'boolean'), ('s', 'string'), ('j', 'json')], default='f', max_length=6),
        ),
    ]
