# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:30


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1020_auto_20161016_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPackageVersionInstallInfo',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField(null=True)),
                ('size', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assetpackageversioninstalltime',
            name='package_version',
        ),
        migrations.RemoveField(
            model_name='assetbatch',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='assetbatch',
            name='packages_install_times',
        ),
        migrations.RemoveField(
            model_name='assetbatch',
            name='packages_install_times_status',
        ),
        migrations.RemoveField(
            model_name='assetbatch',
            name='packages_status',
        ),
        migrations.RemoveField(
            model_name='assetpackageversion',
            name='size',
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='installed_packages_status',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AssetPackageVersionInstallTime',
        ),
        migrations.AddField(
            model_name='assetpackageversioninstallinfo',
            name='package_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.AssetPackageVersion'),
        ),
        migrations.AddField(
            model_name='assetbatch',
            name='installed_packages',
            field=models.ManyToManyField(to='backbone.AssetPackageVersionInstallInfo'),
        ),
    ]
