# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1021_auto_20170108_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmapscan',
            name='devices_found',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='devices_scanned',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='runtime',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
