# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 09:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1023_auto_20170111_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='icsweggconsumer',
            name='ghost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='icsweggcradle',
            name='available_ghost',
            field=models.IntegerField(default=0),
        ),
    ]
