# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1025_icsweggrequest_mult'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmapscan',
            name='devices_ignored',
            field=models.IntegerField(null=True),
        ),
    ]
