# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1025_nmapscan_devices_ignored'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenStaticAssetTemplateTypes',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
