# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1026_auto_20170116_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
