# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1027_auto_20170120_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicelogentry',
            options={'ordering': ('-idx',)},
        ),
        migrations.AddField(
            model_name='mon_check_command',
            name='unique_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mon_check_command',
            name='system_command',
            field=models.BooleanField(default=False),
        ),
    ]
