# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1028_auto_20170124_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config_blob',
            name='config_old',
        ),
        migrations.RemoveField(
            model_name='config_bool',
            name='config_old',
        ),
        migrations.RemoveField(
            model_name='config_int',
            name='config_old',
        ),
        migrations.RemoveField(
            model_name='config_str',
            name='config_old',
        ),
        migrations.RemoveField(
            model_name='mon_check_command',
            name='config_old',
        ),
        migrations.AlterField(
            model_name='mon_check_command',
            name='config',
            field=models.ForeignKey(blank=True, db_column='new_config_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.config'),
        ),
    ]
