# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import initat.md_config_server.base_config.mon_base_config


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1029_auto_20170124_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon_check_command',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='mcc_devices', to='backbone.device'),
        ),
    ]
