# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import initat.md_config_server.base_config.mon_base_config


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1029_auto_20170124_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethwcpuentry',
            name='vendor',
            field=models.TextField(null=True),
        ),
    ]
