# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import initat.md_config_server.base_config.mon_base_config


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1030_auto_20170125_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon_check_command',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
