# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import initat.md_config_server.base_config.mon_base_config


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1031_auto_20170126_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon_check_command_special',
            name='dummy_mcc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mccs_ref', to='backbone.mon_check_command'),
        ),
        migrations.AddField(
            model_name='mon_check_command',
            name='special_shadow',
            field=models.BooleanField(default=False),
        ),
    ]
