# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import initat.md_config_server.base_config.mon_base_config


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1032_auto_20170127_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBStructuredMonBaseConfig',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('backbone.mon_check_command', initat.md_config_server.base_config.mon_base_config.StructuredContentEmitter),
        ),
        migrations.AlterField(
            model_name='mon_check_command_special',
            name='dummy_mcc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mccs_ref', to='backbone.DBStructuredMonBaseConfig'),
        ),
    ]
