# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1033_auto_20170128_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmapscan',
            name='manual_scan',
            field=models.BooleanField(default=False),
        ),
    ]
