# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1034_auto_20170130_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbatch',
            name='manual_scan',
            field=models.BooleanField(default=False),
        ),
    ]
