# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1035_auto_20170131_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='icsweggbasket',
            name='license_id_name',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AlterUniqueTogether(
            name='icsweggbasket',
            unique_together=set([('license', 'license_id_name')]),
        ),
    ]
