# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1036_auto_20170131_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='icsweggconsumer',
            name='license_id_name',
            field=models.CharField(default='', max_length=63),
        ),
    ]
