# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1037_auto_20170131_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icsweggbasket',
            old_name='eggs',
            new_name='available',
        ),
        migrations.AddField(
            model_name='icsweggbasket',
            name='available_ghost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icsweggbasket',
            name='grace_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='icsweggbasket',
            name='grace_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='icsweggbasket',
            name='installed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icsweggbasket',
            name='limit_grace',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icsweggrequest',
            name='egg_basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backbone.icswEggBasket'),
        ),
    ]
