# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


def dummy_reverse(apps, schema_editor):
    pass


def migrate_mcc_config(apps, schema_editor):
    config = apps.get_model("backbone", "config")
    mon_check_command = apps.get_model("backbone", "mon_check_command")
    for mon_c in mon_check_command.objects.all().select_related("config"):
        if mon_c.config_id:
            mon_c.config_rel.add(mon_c.config)
            mon_c.config = None
            mon_c.save(update_fields=["config"])


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1041_auto_20170204_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon_check_command',
            name='config_rel',
            field=models.ManyToManyField(related_name='mcc_rel', to='backbone.config'),
        ),
        migrations.RunPython(migrate_mcc_config, reverse_code=dummy_reverse),
    ]
