# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1044_auto_20170206_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='model_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='object_id',
            field=models.IntegerField(null=True),
        ),
    ]
