# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:51

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def dummy_reverse(apps, schema_editor):
    pass


def fix_commandline_typo(apps, schema_editor):
    mcc = apps.get_model("backbone", "mon_check_command")
    for obj in mcc.objects.all():
        if obj.command_line.startswith("(") and obj.command_line.endswith(",)"):
            obj.command_line = obj.command_line[2:-3]
            obj.save(update_fields=["command_line"])


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1045_auto_20170207_1049'),
    ]

    operations = [
        migrations.RunPython(fix_commandline_typo, reverse_code=dummy_reverse),
    ]
