# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1047_auto_20170210_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendConfigFile',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(choices=[('mcc_json', 'mcc json')], default='mcc_json', max_length=16)),
                ('most_recent', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ("same_uploads", models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='backendconfigfile',
            name='install_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.device'),
        ),
    ]
