# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1048_auto_20170210_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon_check_command',
            name='json_linked',
            field=models.BooleanField(default=False),
        ),
    ]
