# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1049_auto_20170211_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon_icinga_log_last_read',
            name='inode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mon_icinga_log_last_read',
            name='line_number',
            field=models.IntegerField(default=0),
        ),
    ]
