# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1050_auto_20170212_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mon_icinga_log_last_read',
            new_name='MonIcingaLastRead',
        ),
    ]
