# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models


def dummy_reverse(apps, schema_editor):
    pass


def make_config_unique(apps, schema_editor):
    config = apps.get_model("backbone", "config")
    name_dict = {}
    for entry in config.objects.all():
        name_dict.setdefault(entry.name, []).append(entry)
    name_dict = {
        key: value for key, value in name_dict.items() if len(value) > 1
    }
    print("non-unique configs found: {:d}".format(len(name_dict)))
    for name, c_list in name_dict.items():
        for index, entry in enumerate(c_list[1:], 1):
            entry.name = "{}_{:d}".format(entry.name, index)
            entry.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1052_auto_20170213_1321'),
    ]

    operations = [
        migrations.RunPython(make_config_unique, reverse_code=dummy_reverse),
    ]
