# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1056_auto_20170216_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netdevice',
            name='snmp_network_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backbone.snmp_network_type'),
        ),
    ]
