# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1057_auto_20170216_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_variable',
            name='password_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dvs_allowed_name',
            name='password_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device_variable',
            name='var_type',
            field=models.CharField(choices=[('i', 'integer'), ('s', 'string'), ('d', 'datetime'), ('B', 'bool'), ('D', 'Date'), ('t', 'time'), ('b', 'blob'), ('', 'ignore'), ('?', 'guess')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dvs_allowed_name',
            name='forced_type',
            field=models.CharField(choices=[('i', 'integer'), ('s', 'string'), ('d', 'datetime'), ('B', 'bool'), ('D', 'Date'), ('t', 'time'), ('b', 'blob'), ('', 'ignore'), ('?', 'guess')], default='', max_length=3),
        ),
    ]
