# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '1057_auto_20170216_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_variable',
            name='password_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config_script',
            name='description',
            field=models.CharField(blank=True, db_column='descr', max_length=765),
        ),
        migrations.AlterField(
            model_name='populateramdiskcmdline',
            name='idx',
            field=models.AutoField(db_column='kernel_log_idx', primary_key=True, serialize=False),
        ),
    ]
